[libraries]
vunit_lib.files = [
    "../../Utilities/vunit/vunit/vhdl/string_ops/src/string_ops.vhd",
    "../../Utilities/vunit/vunit/vhdl/path/src/path.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/location_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/types.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/event_common_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/event_private_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/data_types_private_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/codec_builder.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/codec.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/codec-2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/ansi_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/dict_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/run/src/run_types.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/dict_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/dict_pkg-2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/data_types_context.vhd",
    "../../Utilities/vunit/vunit/vhdl/core/src/stop_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/core/src/stop_body_2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/core/src/core_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/log_levels_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/common_log_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/file_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/log_handler_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/print_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/print_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/common_log_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/id_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/logger_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/run/src/runner_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/run/src/run_api.vhd",
    "../../Utilities/vunit/vunit/vhdl/logging/src/logger_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/dictionary/src/dictionary.vhd",
    "../../Utilities/vunit/vunit/vhdl/data_types/src/event_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/checker_pkg.vhd",
    "../../Utilities/vunit/vunit/vhdl/vunit_run_context.vhd",
    "../../Utilities/vunit/vunit/vhdl/run/src/run.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/checker_pkg-body.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/check_api.vhd",
    "../../Utilities/vunit/vunit/vhdl/vunit_context.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/check_api-2008p.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/check.vhd",
    "../../Utilities/vunit/vunit/vhdl/check/src/check-2008p.vhd",
]

lib.files = [
    "pl/src/ws_pulse/ws_pulse.vhd",
    "pl/src/wrappers/zynq_bd_wrapper.vhd",
    "pl/src/simulated_array/simulated_array_clk_wiz_wrapper.vhd",
    "pl/src/simulated_array/simulated_array_bram.vhd",
    "pl/src/simulated_array/simulated_array_controller.vhd",
    "pl/test/tb_simulated_array_controller.vhd",
    "pl/src/simulated_array/edge_detect_ws.vhd",
    "pl/src/sample_data/sample.vhd",
    "pl/src/sample_data/double_ff.vhd",
    "pl/src/sample_data/button_index_select.vhd",
    "pl/src/simulated_array/simulated_array.vhd",
    "pl/test/tb_simulated_array.vhd",
    "pl/src/matrix_package.vhd",
    "pl/test/tb_ws_pulse.vhd",
    "pl/test/tb_sample_clk.vhd",
    "pl/src/sample_data/collector.vhd",
    "pl/test/tb_simulated_array_and_sample.vhd",
    "pl/test/tb_collector.vhd",
    "pl/src/decode/ema.vhd",
    "pl/test/tb_ema.vhd",
    "pl/src/decode/decode_ema.vhd",
    "pl/test/tb_decode_ema.vhd",
    "pl/src/channelizer/transposed_folded_fir_dsp.vhd",
    "pl/src/channelizer/transposed_fir_dsp.vhd",
    "pl/src/channelizer/down_sample.vhd",
    "pl/test/tb_down_sample.vhd",
    "pl/src/channelizer/circular_buffer_bram.vhd",
    "pl/src/channelizer/transposed_folded_fir_controller.vhd",
    "pl/src/channelizer/transposed_fir_controller.vhd",
    "pl/test/tb_transposed_fir_downsample.vhd",
    "pl/test/tb_transposed_fir_controller.vhd",
    "pl/src/axi_full/mux.vhd",
    "pl/test/tb_mux.vhd",
    "pl/src/axi_full/fifo_bram.vhd",
    "pl/src/axi_full/fifo_axi.vhd",
    "pl/test/tb_super_test.vhd",
    "pl/test/tb_fifo_axi.vhd",
    "pl/src/wrappers/aw_top.vhd",
    "pl/test/tb_aw_top.vhd",
    "pl/src/axi_full/axi_full_slave.vhd",
    "pl/src/axi_full/axi_full_master.vhd",
    "pl/src/axi_full/axi_full_top.vhd",
]

vunit_lib.is_third_party = true
