[libraries]
vunit_lib.files = [
   "/home/$USER/Utilities/vunit/vunit/vhdl/string_ops/src/string_ops.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/path/src/path.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/print_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/location_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/location_pkg-body-2008m.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/types.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/codec_builder.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/codec_builder-2008p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/codec.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/codec-2008p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/api/external_string_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/ansi_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/log_levels_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pkg-body-2002p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/byte_vector_ptr_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/api/external_integer_vector_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/log_handler_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/print_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/logger_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/dictionary/src/dictionary.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/run/src/run_types.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/file_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/log_handler_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pkg-body-2002p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/integer_array_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/string_ptr_pool_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/queue_pkg-2008p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/integer_vector_ptr_pool_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/run/src/runner_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/run/src/run_api.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/queue_pool_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/integer_array_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/dict_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/data_types/src/data_types_context.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/core/src/stop_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/core/src/stop_body_2008p.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/core/src/core_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/run/src/run.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/logger_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/logging/src/log_levels_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/check/src/checker_pkg.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/vunit_run_context.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/check/src/checker_pkg-body.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/check/src/check_api.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/vunit_context.vhd",
   "/home/$USER/Utilities/vunit/vunit/vhdl/check/src/check.vhd",
]

ljudkriget.files = [
   "pl/src/*.vhd",
   "pl/src/*/*.vhd",
   "pl/test/*.vhd",
   "pl/src/simulated_array/ip_wrappers/*.vhd",
]
